### ISSUE TITLE
Multiple classes

### ISSUE THREAD

**Issue by extsoft** [lvrub/Comments#1]
There are two training in the different room. The first trainer teaches how to use git. The second one demonstrates how to bake a cake. Second room can have only 6 people at the same time while the first one is unlimited. 

Some implementation details: 
- `learn` and `teach` methods has to accept a `subject` as an argument
- If there is no space in the room, proper message is displayed when a room tries to accept the new student.  We don’t learn a student if it is not in the room.

**Comment by lvrub** [comment]
Please review my task  #1
>I'm not sure it's correct but I'would like  get a feedback from you .

**Comment by extsoft** [comment]
@lvrub You don't follow the implementation details described in the task. Please read them again and try to implement one by one.

**Comment by lvrub** [comment]
@extsoft  I've added verification for displaying message when room cann't accept student

**Comment by extsoft** [comment]
@lvrub once you will close #4 and #5, I will review full implementation again and create some tasks if any.
