### ISSUE TITLE
Use proper Java naming

### ISSUE THREAD

**Issue by extsoft** [lvrub/Comments#4]
Use proper java naming  from [https://docs.oracle.com/javase/tutorial/java/nutsandbolts/variables.html](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/variables.html) (`Naming` section) in https://github.com/lvrub/Comments/blob/0a46aa474f83f36a37aa7aaa5c06e9b82c1e64f1/src/main/java/net/commments/sample/DifferentTraining.java

Affects #1

**Comment by lvrub** [comment]
@extsoft  I've corrected name and pushed

[Last commit] (https://github.com/lvrub/Comments/commit/8f0f7120fb5e0c3d15030fa9acef2d040dc9498a)
