### ISSUE TITLE
Update pom.xml

### ISSUE THREAD

**Issue by extsoft** [lvrub/Comments#8]
https://github.com/lvrub/Comments/blob/69a31f53c66f373b786ff3ab02999ee4969cac30/pom.xml#L18
1. please remove the scope
2. please remove all empty lines in dependencies sections (there are some unicode symbols and maven can't parse `pom.xml` on linux system)
3. Please add an empty line at the end of the file.

**Comment by lvrub** [comment]
@extsoft  done, pushed
